regions:
 - us-east-1
keyed_groups:
 - key: tags.Name
   prefix: tag_name_
   separator: ""
 - key: tags.Module
   prefix: tag_Module_
   separator: ""
 - key: tags.Department
   prefix: tag_Department_
   separator: ""
